# Generated by Django 5.1.4 on 2024-12-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('fecha_fabricacion', models.DateField()),
                ('imagen_principal', models.URLField(blank=True, null=True)),
                ('descripcion_principal', models.TextField()),
                ('caracteristicas', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
